matrix:
  - name: Text Files
    aspell:
      lang: en
    dictionary:
      wordcodes:
        - en
      encoding: utf-8
    wordlist:
      - rebase
      - init
      - git
      - gfd
    sources:
      - "**/*.txt"
      - "**/*.md"